account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'
urlpatterns = [
	path('login/', views.login_view, name = 'login'),
	path('register/', views.register_view, name = 'register'),
	path('after_register/<profile_id>/',views.after_register_view, name='after-register'),
	path('logout/', views.logout_view, name = 'logout'),
	path('account/<profile_id>', views.account_view, name = 'account')
]

products/urls.py
from django.urls import path
from . import views
app_name = 'products'
urlpatterns = [
	path('', views.home, name = 'home'),
	path('product/<pr_id>/', views.product_view, name='product'),
	path('product/<pr_id>/delete/', views.delete_product_view, name='product-delete'),
	path('product-sell/', views.sell_product_view, name = 'product-sell'),
	path('categoty-search/<category_name>/', views.category_search_view,name='category-search'),
	path('main-search/', views.main_search_view, name = 'main-search'),
	path('all-search/<localization>/<word>/',views.all_search_view, name = 'all-search'),
	path('all-searching/<localization>/',views.all_search2_view, name = 'all-searching'),
	path('add_favourite/', views.add_favourite_list),
	path('favourites/', views.favourites_view, name = 'favourites'),
	path('chat/<user_id>/<room_name>/', views.room_view, name = 'room'),
	path('messages/', views.messages_view, name = 'messages')
]

wesell/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace = 'products')),
    path('', include('account.urls', namespace = 'account')),
    path('reset_password/', 
        auth_views.PasswordResetView.as_view(template_name="account/password_reset.html"), 
        name="reset_password"),
    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_sent.html'),
        name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_form.html'),
        name="password_reset_confirm"),
    path('reset_password_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_done.html'),
        name= "password_reset_complete")
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

products/models.py
from django.db import models
from account.models import Profile
from .models import *


class Category(models.Model):
	name = models.CharField(max_length=100, null = False, blank=False)
	picture = models.ImageField(upload_to='category_images/')

	def __str__(self):
		return self.name

class City(models.Model):
	name = models.CharField(max_length = 100, null = False, blank=False)
	latitude = models.FloatField()
	longitude = models.FloatField()
	date_cr = models.DateTimeField(auto_now_add = True)

	class Meta:
		ordering=('date_cr',)

	def __str__(self):
		return self.name

class Currency(models.Model):
	name = models.CharField(max_length=50, null=False, blank=False)
	
	def __str__(self):
		return self.name


class Product(models.Model):
	seller = models.ForeignKey(Profile, on_delete = models.SET_NULL, null =True)
	title = models.CharField(max_length = 155, null = False, blank = False)
	category = models.ForeignKey(Category, on_delete = models.SET_NULL, null = True)
	description = models.TextField()
	price = models.IntegerField()
	money_type = models.ForeignKey(Currency, on_delete = models.SET_NULL, null = True)
	localization = models.ForeignKey(City, on_delete = models.SET_NULL, null= True)
	principal_img = models.ForeignKey('Product_Image', on_delete = models.CASCADE, null = True)
	date_posted = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		return f'{self.id}'



class Product_Image(models.Model):
	product_name = models.ForeignKey(Product, on_delete = models.CASCADE)
	image = models.ImageField(upload_to='product_images/')
	
	def __str__(self):
 		return f'{self.product_name.id}'


class Favourite(models.Model):
	user = models.OneToOneField(Profile, on_delete = models.SET_NULL, null=True)
	products = models.ManyToManyField(Product)

	def __str__(self):
		return str(self.id)


class ChatRoomName(models.Model):
	name = models.CharField(max_length= 255)
	date_created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.name

class Message(models.Model):
	user_id = models.CharField(max_length = 255)
	room = models.ForeignKey(ChatRoomName, on_delete=models.CASCADE,null=True,max_length = 255)
	content = models.TextField()
	data_added = models.DateTimeField(auto_now_add= True)

	class Meta:
		ordering = ('data_added', )

	def __str__(self):
		return str(self.id)

products/views.py
from django.shortcuts import render, redirect
from .models import *
import json
from django.http import JsonResponse, HttpResponse
from django.contrib import messages
from account.models  import *
import pandas as pd

def home(request):
	context = {}
	'''
	f = open('C:/Users/adran/Desktop/WeSell/src/products/coord.txt', 'r')
	ll = []
	for line in f:
		stripped_line = line.strip()
		ll.append([stripped_line])
	l2 = []
	for x in ll:
		for i in x:
			i = i.replace('\t', '')
			i = i.replace("°", '.')
			i = i.replace("'", '')
			i = i.replace("Â", '')
			l2.append(i.split())
	l3 = []
	for j in l2:
		if len(j) == 4:
			j[0] = j[0]+ ' ' +j[1]
			j.remove(j[1])
		elif len(j) == 5:
			j[0] = j[0] + ' ' + j[1] + j[2]
			j.remove(j[1])
			j.remove(j[2])
		l3.append(j)
	print(l3)
	for city in l3:
		City.objects.create(name = city[0], latitude = city[1], longitude = city[2])
	'''
	products = Product.objects.all()
	categories = Category.objects.all()
	counties = City.objects.all()
	if request.user.is_authenticated:
		last_list = []
		for i in products:
			dictt={
			'product':'',
			'is_fav' : '' 
			}
			req_profile = Profile.objects.get(pk=request.user.id)
			is_fav = False
			favourite = Favourite.objects.get(user = req_profile)
			if i in favourite.products.all():
				is_fav = True
			dictt['product'] = i
			dictt['is_fav'] = is_fav
			last_list.append(dictt)
		context['all_products'] = last_list
	else:
		context['products'] = products
	context['products'] = products
	context['counties'] = counties
	context['categories'] = categories
	return render(request, 'products/home.html', context)

def product_view(request, pr_id):
	context = {}
	product = Product.objects.get(pk = pr_id)
	product_images = Product_Image.objects.filter(product_name = product.id)
	if request.user.is_authenticated:
		req_profile = Profile.objects.get(pk=request.user.id)
		is_fav = False
		favourite = Favourite.objects.get(user = req_profile)
		if product in favourite.products.all():
			is_fav = True
		context['is_fav'] = is_fav
		
		all_chats  = ChatRoomName.objects.all()
		all_rooms= []
		for i in all_chats:
			all_rooms.append(i.name)
		req_id = request.user.id
		seller_id = product.seller.id
		product_id = pr_id
		first_option = f"{req_id}_{seller_id}_{product_id}" 
		second_option = f"{seller_id}_{req_id}_{product_id}"
		if first_option in all_rooms:
			room_q = ChatRoomName.objects.get(name = first_option)
			context['room_name'] = room_q
		elif second_option in all_rooms:
			room_q = ChatRoomName.objects.get(name = second_option)
			context['room_name'] = room_q
		else:
			if req_id != seller_id:
				room_q = ChatRoomName(name = first_option)
				room_q.save()
				context['room_name'] = room_q
		is_req = False
		if request.user.id == product.seller.id:
			is_req = True 
		context['is_req'] = is_req
	context['product'] = product
	context['product_images'] = product_images
	return render(request, 'products/product_page.html', context)
def delete_product_view(request, pr_id):
	product = Product.objects.get(pk=pr_id)
	all_rooms = ChatRoomName.objects.all()
	for i in all_rooms:
		name = i.name
		result = name.split('_')
		if result[2] == str(pr_id):
			i.delete()
	product.delete()
	return redirect('account:account', profile_id=request.user.id)




def sell_product_view(request):
	context = {}
	categories = Category.objects.all()
	counties = City.objects.all()
	currencies = Currency.objects.all()
	account = Profile.objects.get(pk = request.user.id)
	if request.POST:
		seller = Profile.objects.get(pk = request.user.id)
		title = request.POST['title']
		category = Category.objects.get(name = request.POST['category-choose'])
		description = request.POST['description-fill']
		price = request.POST['price']
		money_type = Currency.objects.get(name = request.POST['money-type'])
		localization = City.objects.get(name = request.POST['coming-from'])
		product = Product.objects.create(
			seller = seller,
			title = title,
			category = category,
			description = description,
			price = price,
			money_type = money_type,
			localization = localization
			)
		images = request.FILES.getlist('image-upload')
		pr_name = Product.objects.get(pk=product.id)
		for image in images:
			photo = Product_Image.objects.create(
				product_name = pr_name,
				image = image
				)
		product.principal_img = Product_Image.objects.filter(product_name = product.id)[0]
		product.save()
		messages.success(request, 'Your announcement has been added!')
		return redirect('products:product', pr_id=product.id)
	context['account'] = account
	context['counties'] = counties
	context['categories'] = categories
	context['currencies'] = currencies
	return render(request, 'products/sell_product.html', context)

def category_search_view(request, category_name):
	context = {}
	category = Category.objects.get(name = category_name)
	products = Product.objects.filter(category = category)
	if request.user.is_authenticated:
		last_list = []
		for i in products:
			dictt={
			'product':'',
			'is_fav' : '' 
			}
			req_profile = Profile.objects.get(pk=request.user.id)
			is_fav = False
			favourite = Favourite.objects.get(user = req_profile)
			if i in favourite.products.all():
				is_fav = True
			dictt['product'] = i
			dictt['is_fav'] = is_fav
			last_list.append(dictt)
		context['all_products'] = last_list
	else:
		context['products'] = products
	products_len = len(products)
	context['products_len'] = products_len
	context['category'] = category
	return render(request, 'products/category_search.html', context)

def main_search_view(request):
	context = {}
	if request.POST:
		main_search = request.POST['main-search']
		local = request.POST['selecting']
		if len(main_search) > 0:
			return redirect('products:all-search', localization=local, word=main_search)
		else:
			return redirect('products:all-searching', localization=local)

def all_search2_view(request, localization):
	context = {}
	localization = City.objects.get(name = localization)
	products = Product.objects.filter(localization = localization)
	last_list = []
	for i in products:
		last_list.append(i)
	if request.user.is_authenticated:
		l_l = []
		for i in last_list:
			dictt={
			'product':'',
			'is_fav' : '' 
			}
			req_profile = Profile.objects.get(pk=request.user.id)
			is_fav = False
			favourite = Favourite.objects.get(user = req_profile)
			if i in favourite.products.all():
				is_fav = True
			dictt['product'] = i
			dictt['is_fav'] = is_fav
			l_l.append(dictt)
		context['all_dicts'] = l_l
	else:
		context['products'] = last_list
	context['products_len'] = len(last_list)
	context['local'] = localization
	return render(request, 'products/all-search2.html', context)

def all_search_view(request, localization, word):
		context = {}
		localization = City.objects.get(name = localization)
		search_results = Product.objects.filter(title__icontains=word)
		last_list = []
		for i in search_results:
			if localization != 'All Country':
				if i.localization == localization:
					last_list.append(i)
			else:
				last_list.append(i)
		if request.user.is_authenticated:
			l_l = []
			for i in last_list:
				dictt={
				'product':'',
				'is_fav' : '' 
				}
				req_profile = Profile.objects.get(pk=request.user.id)
				is_fav = False
				favourite = Favourite.objects.get(user = req_profile)
				if i in favourite.products.all():
					is_fav = True
				dictt['product'] = i
				dictt['is_fav'] = is_fav
				l_l.append(dictt)
			context['all_dicts'] = l_l
		else:
			context['products'] = last_list
		context['products_len'] = len(last_list)
		context['main_search'] = word
		context['local'] = localization
		return render(request, 'products/all_search.html', context)

def add_favourite_list(request):
	data = json.loads(request.body)
	productId = data['productId']
	action = data['action']
	profile = Profile.objects.get(pk = request.user.id)
	product = Product.objects.get(pk = productId)
	favourite, created = Favourite.objects.get_or_create(user = profile)
	if action == "add":
		favourite.products.add(product)
	elif action == "remove":
		favourite.products.remove(product)
	favourite.save()
	return JsonResponse('item was added', safe = False)


def favourites_view(request):
	context = {}
	if request.user.is_authenticated:
		req_profile = Profile.objects.get(pk=request.user.id)
		favourite = Favourite.objects.get(user = req_profile)
		fav_products = favourite.products.all()
		last_list = []
		for i in fav_products:
			last_list.append(i)
		context['products'] = last_list
	return render(request, 'products/favourites.html',context)

def room_view(request, room_name, user_id):
	context = {}
	if request.user.is_authenticated:
		user_id = request.user.id
		room = ChatRoomName.objects.get(name = room_name)
		all_messages = Message.objects.filter(room = room)
		mesaje = []
		for i in all_messages:
			mes_dict = {
			'mesaj' : '',
			'is_same':''
			}
			is_same = False
			if str(i.user_id) == str(request.user.id):
				is_same = True
			mes_dict['mesaj'] = i
			mes_dict['is_same'] = is_same
			mesaje.append(mes_dict)
			context['mesaje'] = mesaje
		if len(room_name) == 5:
			product_number = room_name[-1]
		elif len(room_name) == 6:
			product_number = room_name[-2:]
		elif len(room_name) == 7:
			product_number = room_name[-3:]
		product = Product.objects.get(pk = product_number)
		context['product'] = product
		context['user_id'] = user_id
		context['room_name'] =room_name
	return render(request, 'products/room.html', context)

def messages_view(request):
	context = {}
	chat_r = ChatRoomName.objects.all()
	pk = request.user.id 
	rooms = []
	for i in chat_r:
		rooms.append(i.name)
	final_list = []
	for j in rooms:
		chat_dict = {
			'room' : '',
			'user' : '',
			'product' : ''
		}
		word = j.split('_')
		if word[0] == str(pk) or word[1] == str(pk): 
			valid_room = ChatRoomName.objects.get(name = j)
			if word[0] == str(pk):
				user_id = word[1]
			elif word[1] == str(pk):
				user_id = word[0]
			user = Profile.objects.get(pk = user_id)

products/templates/products/all-search2.html
{% extends 'products/main.html' %}
{% load static %}
{% block content %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/products/all-search2.css' %}">
	<div class="products">
		<div class="start-text">	
			<h2>Search for announces in "{{local}}": </h2>
			<p><b>{{products_len}}</b> announces</p>
		</div>
		{% if all_dicts %}
			{% for dict in all_dicts %}
				<div class="product">
					<div class="img-div">
						<a href="{% url 'products:product' pr_id=dict.product.id %}"><img id="imggg" src="{{dict.product.principal_img.image.url}}"></a>
					</div>
					<div class="title-div">
						<a href="{% url 'products:product' pr_id=dict.product.id%}" id="title">{{dict.product.title}}</a>
						<p id="localization">{{dict.product.localization}},  {{dict.product.date_posted}}</p>
					</div>
					<div class="price-div">
						<p><b>{{dict.product.price}}</b>  {{dict.product.money_type}}</p>
						{% if dict.is_fav %}
							<i class="fa fa-heart favourite" data-action="remove" data-product="{{dict.product.id}}" aria-hidden="true"></i>
						{% else %}
							<i data-action="add" data-product="{{dict.product.id}}" class="fa fa-heart-o favourite" aria-hidden="true"></i>
						{% endif %}
					</div>
				</div>	
			{% endfor %}
		{% else %}
			{% for product in products %}
				<div class="product">
					<div class="img-div">
						<a href="{% url 'products:product' pr_id=product.id %}"><img id="imggg" src="{{product.principal_img.image.url}}"></a>
					</div>
					<div class="title-div">
						<a href="{% url 'products:product' pr_id=product.id%}" id="title">{{product.title}}</a>
						<p id="localization">{{product.localization}},  {{product.date_posted}}</p>
					</div>
					<div class="price-div">
						<p><b>{{product.price}}</b>  {{product.money_type}}</p>
						
							<i data-action="add" data-product="{{product.id}}" class="fa fa-heart-o favourite" aria-hidden="true"></i>
					</div>
				</div>	
			{% endfor %}
		{% endif %}
		{% if not all_dicts and not products %}
			<img id="empty" src="{% static 'used_images/no_search.png' %}">
			<p id="txtt">No search found...</p>
		{% endif %}
	</div>
	<script src="{% static 'js/favouriteAdd.js' %}"></script>
{% endblock content %}

products/templates/products/home.html
{% extends 'products/main.html' %}
{% load static %}
{% block content %}

	<link rel="stylesheet" type="text/css" href="{% static 'css/products/home.css' %}">
	<style type="text/css">
		.anunturi{
			margin-bottom: 4rem;
		}
		@media only screen and (max-width: 900px){
			.whole-search{
				width: 95%;
			}
			.left-search{
				width: 50%;
			}
			#main-src{
				width: 100%;
			}
			.options{
				width: 40%;
			}
			.selection{
				width: 100%;
			}
			#btn-text{
				display: none;
			}

		}
	</style>
		<form action="{% url 'products:main-search' %}"  method="POST">
		{% csrf_token %}
		<div class="search-part">
			<div class="whole-search">	
				<div class="left-search">
					<i class="fa fa-search" aria-hidden="true" style="font-size: 40px;"></i>
					<input id="main-src" type="text" name="main-search" placeholder="Search..">
				</div>
				<div class="center-search">
					<i class="fa fa-map-marker" aria-hidden="true" style="font-size: 40px;"></i>
				<div class="options">
					<select name="selecting" class="selection">
						{% for county in counties%}
							<option>{{county}}</option>
						{% endfor %}
					</select>
				</div>
				</div>
				<div class="right-search">
					<button type="submit" id="search-btn">
						<p id="btn-text">Search</p>
						<i class="fa fa-search" aria-hidden="true" style="font-size: 40px;"></i>
					</button>
				</div>
			</div>
		</div>
	</form>
	<div id="cat-text">
		<p id="category-text">Categories:</p>
	</div>
	<div class="categories">
		{% for category in categories %}
		<div class="category">
			<a href="{% url 'products:category-search' category_name=category.name %}"><img id="category-image" src="{{category.picture.url}}"></a>
			<a href="{% url 'products:category-search' category_name=category.name %}"><p id="text-1">{{category.name}}</p></a>
		</div>
		{% endfor %}
	</div>
	<div class="an-text">
			<p id="an-text2">Announcements:</p>
		</div>
	<div class="anunturi">
			{% if all_products %}
				{% for dict in all_products %}
				<div class="anunt">
					<a href="{% url 'products:product' pr_id=dict.product.id %}"><img id="anunt-img" src="{{dict.product.principal_img.image.url}}"></a>
					<a id="anunt-title" href="{% url 'products:product' pr_id=dict.product.id %}">{{dict.product.title}}</a>
					<p id="anunt-country">{{dict.product.localization}}. {{dict.product.date_posted|date:"d M, Y"}}</p>
					<div class="price-and-heart">
						<p id="anunt-price">{{dict.product.price}} {{dict.product.money_type}}</p>
						{% if dict.is_fav %}
							<i class="fa fa-heart favourite" data-action="remove" data-product="{{dict.product.id}}" aria-hidden="true"></i>
						{% else %}
							<i data-action="add" data-product="{{dict.product.id}}" class="fa fa-heart-o favourite" aria-hidden="true"></i>
					{% endif %}	
					</div>
					
				</div>
				{% endfor %}
			{% else %}
				{% for product in products %}
				<div class="anunt">
					<a href="{% url 'products:product' pr_id=product.id %}"><img id="anunt-img" src="{{product.principal_img.image.url}}"></a>
					<a id="anunt-title" href="{% url 'products:product' pr_id=product.id %}">{{product.title}}</a>
					<p id="anunt-country">{{product.localization}}. {{product.date_posted|date:"d M, Y"}}</p>
					<div class="price-and-heart">
						<p id="anunt-price">{{product.price}} {{product.money_type}}</p>
						<i class="fa fa-heart-o favourite" aria-hidden="true"></i>	
					</div>
					
				</div>
				{% endfor %}
			{% endif %}
	</div>
	<script src="{% static 'js/favouriteAdd.js' %}"></script>
{% endblock content %}

products/templates/products/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta name="viewport" content="width=device-width initial-scale=1.0">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Stick+No+Bills:wght@300;800&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="shortcut icon" type="image/ico" href="{% static 'used_images/faviconn.ico' %}">
	<title>
		WeSell
	</title>
	<style>
		::-webkit-scrollbar {
			width: 15px;
		} 
		
		::-webkit-scrollbar-thumb{
			border-radius: 5px;
			background-color: grey;
		}
		html{
			scroll-behavior: smooth;
		}
	</style>
</head>
<body>
	<link rel="stylesheet" type="text/css" href="{% static 'css/products/main.css' %}">
	<script type="text/javascript">
		var user = "{{request.user}}"
		function getToken(name) {
	    let cookieValue = null;
	    if (document.cookie && document.cookie !== '') {
	        const cookies = document.cookie.split(';');
	        for (let i = 0; i < cookies.length; i++) {
	            const cookie = cookies[i].trim();
	            if (cookie.substring(0, name.length + 1) === (name + '=')) {
	                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
	                break;
	            }
	        }
	    }
	    return cookieValue;
		}
		const csrftoken = getToken('csrftoken');
	</script>
	<div class="nav">
		<div class="left-side">
			<a id="logo" href="{% url 'products:home' %}">WeSell</a>
		</div>
		<div class="right-side">
			<div class="nav-component">
				<a class="a-tag"> 
					{% if request.user.is_authenticated %}
						<a class="a-tag" href="{% url 'products:messages' %}">
							<i class="fa fa-commenting-o" aria-hidden="true" style="font-size:20px;"></i>
							<p class="nav-text">Messages</p>
						</a>
					{% else %}
						<a class="a-tag" href="{% url 'account:login' %}">
							<i class="fa fa-commenting-o" aria-hidden="true" style="font-size:20px;"></i>
							<p class="nav-text">Messages</p>
						</a>
					{% endif %}
				</a>
			</div>
			<div class="nav-component">
				{% if request.user.is_authenticated %}
					<a class="a-tag3" href="{% url 'products:favourites' %}"><i class="fa fa-heart-o" aria-hidden="true" style="font-size:20px"></i></a>
					<p id="fav-nr">{{fav_number}}</p>
				{% else %}
					<a class="a-tag3" href="{% url 'account:login' %}"><i class="fa fa-heart-o" aria-hidden="true" style="font-size:20px"></i></a>
				{% endif %}

			</div>
			<div class="nav-component">
				{% if request.user.is_authenticated %}
				<div class="dropdown">
					<a class="a-tag" onclick="dropdownFunction();" style="cursor: pointer;">
						<i class="fa fa-user-o a-tag" aria-hidden="true" style="font-size:20px"></i>
						<p class="nav-text a-tag">Account</p>
					</a>	
					<div id="myDropdown" class="dropdown-content">
						<a href="{% url 'account:account' profile_id=request.user.id %}" style="color: #000;">{{request.user.username}} </a>
						<hr style="width:100%; height: 1px;">
						<a href="{% url 'account:logout' %}">Logout</a>
					</div>
				</div>
				
				{% else %}
				<a class="a-tag" href="{% url 'account:login' %}">
					<i class="fa fa-user-o" aria-hidden="true" style="font-size:20px"></i>
					<p class="nav-text">Account</p>
				</a>
				{% endif %}
			</div>
			<div class="nav-component">
				{% if request.user.is_authenticated %}
				<a href="{% url 'products:product-sell' %}" class="nav-button">
					Sell Anything
				</a>
				{% else %}
				<a href="{% url 'account:login' %}" class="nav-button">
					Sell Anything
				</a>
				{% endif %}
			</div>
		</div>
	</div>
	{% if messages %}
		{% for message in messages %}
			<div class="alert {{message.tags}}" id="msg" role='alert'>
				{{ message }}
			</div>
		{% endfor %}
	{% endif %}
	{% block content %}
	{% endblock content %}
	<script>
	window.setTimeout("closeHelpDiv();", 3000);

	function closeHelpDiv(){
		document.getElementById("msg").style.display=" none";
	}

	function dropdownFunction() {
			  document.getElementById("myDropdown").classList.toggle("show");
			}

			window.onclick = function(event) {
			  if (!event.target.matches('.a-tag')) {
			    var dropdowns = document.getElementsByClassName("dropdown-content");
			    var i;
			    for (i = 0; i < dropdowns.length; i++) {
			      var openDropdown = dropdowns[i];
			      if (openDropdown.classList.contains('show')) {
			        openDropdown.classList.remove('show');
			      }
			    }
			  }
			}
	</script>
</body>
</html>

products/templates/products/messages.html
{% extends 'products/main.html' %}
{% load static %}
{% block content %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/products/messages.css' %}">
	<style type="text/css">
		.empty{
			height: auto;
			width: 50%;
			margin: 0 auto;
			display: flex;
			flex-direction: column;
			justify-content: center;
			align-items: center;
		}
		#empty-img{
			width: 200px;
			height: 200px;
		}
		.empty p{
			font-weight: bold;
			font-size: x-large;
		}
	</style>
	<div class="white-part">
		<p class="simple-text">Messages:</p>
	</div>
	<div class="grey-part">
	{% if chat_dicts %}
		<div class="antet">
			<p>Name of the user:</p>
			<p>Announcement:</p>
			<p>Date Sent:</p>
		</div>
		{% for dict in chat_dicts %}
		
		<a href="{% url 'products:room' user_id=request.user.id room_name=dict.room.name %}" class="mesaj">
				<p>{{dict.user.user.username}}</p>
				<p>{{dict.product.title}}</p>
				<p>{{dict.room.date_created|date:"d M, g:i"}}</p>
		</a>
		{% endfor %}
		</div>
		{% else %}
			<div class="empty">
				<img id="empty-img" src="{% static 'used_images/no_messages.png' %}">
				<p>You don't have any messages</p>
			</div>
		{% endif %}
	
{% endblock content %}